[2025-02-02T04:31:48.506+0000] {processor.py:186} INFO - Started process (PID=3051) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:48.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:31:48.511+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:31:48.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:48.558+0000] {logging_mixin.py:190} INFO - Generated 50 rows of account dimension data in ./account_dim_large_data.csv
[2025-02-02T04:31:48.563+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:31:48.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:31:48.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:48.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 0.124 seconds
[2025-02-02T04:31:49.707+0000] {processor.py:186} INFO - Started process (PID=3061) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:49.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:31:49.712+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:31:49.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:49.723+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:31:49.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:31:49.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:31:49.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 0.076 seconds
[2025-02-02T04:33:48.738+0000] {processor.py:186} INFO - Started process (PID=3099) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:33:48.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:33:48.755+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:33:48.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:33:48.772+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:33:48.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:33:48.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:33:49.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 0.517 seconds
[2025-02-02T04:34:19.819+0000] {processor.py:186} INFO - Started process (PID=3393) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:34:19.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:34:19.823+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:34:19.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:34:19.829+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:34:19.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:34:19.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:34:19.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 0.043 seconds
[2025-02-02T04:35:14.482+0000] {processor.py:186} INFO - Started process (PID=3668) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:35:14.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:35:14.561+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:35:14.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:35:14.604+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:35:14.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:35:14.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:35:15.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 2.388 seconds
[2025-02-02T04:40:57.268+0000] {processor.py:186} INFO - Started process (PID=3905) to work on /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:40:57.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator.py for tasks to queue
[2025-02-02T04:40:57.272+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:40:57.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:40:57.281+0000] {logging_mixin.py:190} INFO - [2025-02-02T04:40:57.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator.py", line 64, in <module>
    with DAG('account_dim_generator',
         ^^^
NameError: name 'DAG' is not defined
[2025-02-02T04:40:57.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator.py
[2025-02-02T04:40:57.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator.py took 0.068 seconds
