[2025-02-02T06:17:48.620+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:17:48.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:17:48.626+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:17:48.631+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:17:48.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:17:48.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.053 seconds
[2025-02-02T06:18:18.766+0000] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:18.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:18.768+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:18.771+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:18:18.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:18.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.032 seconds
[2025-02-02T06:18:49.271+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:49.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:49.275+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:49.277+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:18:49.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:18:49.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.036 seconds
[2025-02-02T06:19:19.691+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:19.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:19.694+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:19.697+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:19:19.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:19.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.034 seconds
[2025-02-02T06:19:50.029+0000] {processor.py:186} INFO - Started process (PID=1404) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:50.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:50.032+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:50.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:50.035+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:50.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:19:50.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:19:50.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.033 seconds
[2025-02-02T06:20:20.265+0000] {processor.py:186} INFO - Started process (PID=1710) to work on /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:20:20.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/account_dim_generator_dag.py for tasks to queue
[2025-02-02T06:20:20.269+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:20:20.271+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/account_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/account_dim_generator_dag.py", line 8, in <module>
    from scripts.account_dim_generator import generate_account_dim_data
ModuleNotFoundError: No module named 'scripts.account_dim_generator'
[2025-02-02T06:20:20.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/account_dim_generator_dag.py
[2025-02-02T06:20:20.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/account_dim_generator_dag.py took 0.032 seconds
