[2025-02-02T06:17:48.524+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:17:48.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:17:48.531+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:17:48.539+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:17:48.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:17:48.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.057 seconds
[2025-02-02T06:18:18.644+0000] {processor.py:186} INFO - Started process (PID=474) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:18.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:18.646+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:18.650+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:18:18.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:18.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.031 seconds
[2025-02-02T06:18:49.206+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:49.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:49.210+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:49.214+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.213+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:18:49.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:18:49.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.038 seconds
[2025-02-02T06:19:19.578+0000] {processor.py:186} INFO - Started process (PID=1086) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:19.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:19.581+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:19.584+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:19:19.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:19.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.032 seconds
[2025-02-02T06:19:49.922+0000] {processor.py:186} INFO - Started process (PID=1392) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:49.923+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:49.926+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:49.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:49.929+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:49.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:19:49.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:19:49.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.036 seconds
[2025-02-02T06:20:20.150+0000] {processor.py:186} INFO - Started process (PID=1698) to work on /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:20:20.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_dim_generator_dag.py for tasks to queue
[2025-02-02T06:20:20.153+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:20:20.157+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_dim_generator_dag.py", line 9, in <module>
    from scripts.customer_dim_generator import generate_customer_dim_data
ModuleNotFoundError: No module named 'scripts.customer_dim_generator'
[2025-02-02T06:20:20.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_dim_generator_dag.py
[2025-02-02T06:20:20.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_dim_generator_dag.py took 0.037 seconds
