[2025-02-13T15:27:25.118+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schema_dag.submit_schemas scheduled__2025-01-23T17:00:00+00:00 [queued]>
[2025-02-13T15:27:25.127+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schema_dag.submit_schemas scheduled__2025-01-23T17:00:00+00:00 [queued]>
[2025-02-13T15:27:25.128+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 4
[2025-02-13T15:27:25.144+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotSchemaSubmitOperator): submit_schemas> on 2025-01-23 17:00:00+00:00
[2025-02-13T15:27:25.153+0000] {standard_task_runner.py:57} INFO - Started process 48352 to run task
[2025-02-13T15:27:25.157+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'schema_dag', 'submit_schemas', 'scheduled__2025-01-23T17:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/schema_dag.py', '--cfg-path', '/tmp/tmpw_9o_xl2']
[2025-02-13T15:27:25.158+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask submit_schemas
[2025-02-13T15:27:25.213+0000] {task_command.py:415} INFO - Running <TaskInstance: schema_dag.submit_schemas scheduled__2025-01-23T17:00:00+00:00 [running]> on host 5879df32f101
[2025-02-13T15:27:25.295+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hoyseiha@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='schema_dag' AIRFLOW_CTX_TASK_ID='submit_schemas' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T17:00:00+00:00'
[2025-02-13T15:27:25.304+0000] {pinot_schema_operator.py:36} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /schemas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb58f801f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-02-13T15:27:25.313+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=schema_dag, task_id=submit_schemas, execution_date=20250123T170000, start_date=20250213T152725, end_date=20250213T152725
[2025-02-13T15:27:25.334+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-13T15:27:25.354+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
